### ISSUE TITLE
login

### ISSUE THREAD

**Issue by eMaurits** [pronamic/twinfield#22]
Hi,
When i use the oauth way of signing in to twinfield i get an error in the login file.
It says that the function print_pre on line 106 in Twinfield\Secure\login.php isnt found.
I cant find anything else on the function either.
Can you help me with this error?

regards

**Comment by mmolhoek** [comment]
i created a pull request to remove that line. print_pre is a function i have in one of my other libraries, but is not available here.

**Comment by mmolhoek** [comment]
https://github.com/pronamic/twinfield/pull/23

**Comment by bertjuuhh** [comment]
If i comment out that line it leaves me with the error 'sorry, temp_token not set'.
So i'm thinking it's a bit important to have
