### ISSUE TITLE
create new invoice ?

### ISSUE THREAD

**Issue by alirezarahmani** [pronamic/twinfield#27]
@remcotolsma  When i want to create my own invoice the code return error : " `An item code must be specified.//Item code not found.` " then what is the problem with my code:

``` php
$config = new Config();
$config->setCredentials('NLG0','password','TWF-SAAS','NLA001498');
$invoice= new Invoice();

$line=new InvoiceLine();
$line->setQuantity(10)
    ->setValueExcl(100)
    ->setUnits(1)
    ->setVatCode('VH')
    ->setUnitsPriceExcl(100)
    ->setItem('1000')
    ;

$invoice
    ->setCustomer($customerFactory->get('1013'))
    ->setBank('BNK')
    ->setDueDate('20150429')
    ->setPeriod('2015/12')
    ->setCurrency('EUR')
    ->setStatus('concept')
    ->setInvoiceDate('20150425')
    ->addLine($line)
    ->setPaymentMethod('cash')
    ->setInvoiceType('FACTUUR');

$invoiceFactory = new InvoiceFactory($config);
var_dump($invoiceFactory->send($invoice));

```

I mean what is item code , where should set it?

**Comment by alirezarahmani** [comment]
@mmolhoek

**Comment by stephangroen** [comment]
Late to the party, but since this is not closed yet: InvoiceLine requires an article code by using `$line->setArticle($code);`

The article you want to invoice has to exist in Twinfield. If you do not want this you can use an article code of `0` or `-` which allows for free entry.

**Comment by basvandertogt** [comment]
Do i need additional permissions in Twinfield? All getters are working but the setters not. I don't get any error. Just false as response.

**Comment by remcotolsma** [comment]
We are currently cleaning up old open issues within the @pronamic organization and that is how we came across this issue, this may already have been resolved in the https://github.com/php-twinfield/twinfield library.
