### ISSUE TITLE
Send request always returns (false)

### ISSUE THREAD

**Issue by WebLenn** [pronamic/twinfield#30]
Hi fellow developers,

I've been trying to use this PHP library for the Twinfield Integration.
I started by using the example code in the readme.md to add a test customer to my Twinfield account.

After reading the readme.md and looking into the PHP library, i wrote the following code below.
What i didn't understand is the way the files should be included, and i think this might cause my problem.

I did use error_logging to check if any required files or classes where not found but after including all these files in my script i got no more error's.

Can someone maybe give me push in the right direction ?

Thanks in advance,

Kind Regards,

Lennart

```
include "Pronamic/Twinfield/SoapClient.php";
include "Pronamic/Twinfield/Secure/Config.php";
include "Pronamic/Twinfield/Secure/Login.php";
include "Pronamic/Twinfield/Secure/Service.php";
include "Pronamic/Twinfield/Request/Catalog/Catalog.php";
include "Pronamic/Twinfield/Request/Catalog/Dimension.php";
include "Pronamic/Twinfield/Customer/Customer.php";
include "Pronamic/Twinfield/Customer/CustomerAddress.php";
include "Pronamic/Twinfield/Customer/CustomerBank.php";
include "Pronamic/Twinfield/Factory/ParentFactory.php";
include "Pronamic/Twinfield/Customer/DOM/CustomersDocument.php";
include "Pronamic/Twinfield/Customer/CustomerFactory.php";
include "Pronamic/Twinfield/Response/Response.php";
include "Pronamic/Twinfield/Customer/Mapper/CustomerMapper.php";

if (class_exists( '\Pronamic\Twinfield\Secure\Config' )){
    $config = new \Pronamic\Twinfield\Secure\Config();
    $config->setCredentials('API000053', 'mypasswordhere', 'TWF-SAAS', 'nlA001651');

    $customer = new \Pronamic\Twinfield\Customer\Customer();
    $customer
        ->setCode(10666)
        ->setName('Lennart Tester')
        ->setType('DEB')
        ->setWebsite('http://webverder.nl')
        ->setEBilling(true)
        ->setEBillMail('lennart@webverder.nl')
        ->setVatCode('VL')
        ->setDueDays(10);

    $customerAddress = new \Pronamic\Twinfield\Customer\CustomerAddress();
    $customerAddress
        ->setDefault(false)
        ->setType('invoice')
        ->setField1('Testing field 1')
        ->setField2('Testing field 2')
        ->setField3('Testing field 3')
        ->setPostcode('1212 AB')
        ->setCity('TestCity')
        ->setCountry('NL')
        ->setTelephone('010-12345')
        ->setFax('010-1234')
        ->setEmail('test@email.com');

    $customer->addAddress($customerAddress);

    // Config object prepared and passed to the CustomerFactory
    $customerFactory = new \Pronamic\Twinfield\Customer\CustomerFactory($config);

    //$customer = new TwinfieldCustomer\Customer();

    // Attempt to send the Customer document
    if($customerFactory->send($customer)){
        // Use the Mapper to turn the response back into a TwinfieldCustomer\Customer
        $successfulCustomer = \Pronamic\Twinfield\Customer\Mapper\CustomerMapper::map($customerFactory->getResponse());
    } else {
        var_dump($customerFactory->send($customer));
        echo 'DATA NIET JUIST GEIMPORTEERD!! <br /><br />';

        print_r($customer);
    }

    // // Config object prepared and passed into the CustomerFactory
    // $customerFactory = new \Pronamic\Twinfield\Customer\CustomerFactory($config);

    // $customers = $customerFactory->listAll();

} else {
    echo 'CLASS NOT FOUND!';
}
```

**Comment by EmileBons** [comment]
```php
if($customerFactory->send($customer)){
    // Use the Mapper to turn the response back into a TwinfieldCustomer\Customer
    $successfulCustomer = \Pronamic\Twinfield\Customer\Mapper\CustomerMapper::map($customerFactory->getResponse());
} else {
    var_dump($customerFactory->send($customer));
}
```
This does not make so much sense. I would say `send($customer)` would return `false` otherwise it wouldn't end in the else-part of the if-statement. I would suggest starting to debug by checking `$customerFactory->getResponse();` in the else-part of the if-condition.

**Comment by WebVerder** [comment]
Hi Emile,

Thanks for your reply, sorry for my late response had a pretty stressful week.
The reason i put the var_dump($customerFactory->send($customer)); in the else loop is because i noticed it returned false so i wanted to see the exact respons(not very logical indeed).

I've tried your tip and the data that i get back is the following:

```
Pronamic\Twinfield\Response\Response Object
(
    [responseDocument:Pronamic\Twinfield\Response\Response:private] => DOMDocument Object
        (
            [doctype] => 
            [implementation] => (object value omitted)
            [documentElement] => (object value omitted)
            [actualEncoding] => 
            [encoding] => 
            [xmlEncoding] => 
            [standalone] => 1
            [xmlStandalone] => 1
            [version] => 1.0
            [xmlVersion] => 1.0
            [strictErrorChecking] => 1
            [documentURI] => /home/mydomain/domains/webverder.nl/public_html/egm/Twinfield/
            [config] => 
            [formatOutput] => 
            [validateOnParse] => 
            [resolveExternals] => 
            [preserveWhiteSpace] => 1
            [recover] => 
            [substituteEntities] => 
            [nodeName] => #document
            [nodeValue] => 
            [nodeType] => 9
            [parentNode] => 
            [childNodes] => (object value omitted)
            [firstChild] => (object value omitted)
            [lastChild] => (object value omitted)
            [previousSibling] => 
            [attributes] => 
            [ownerDocument] => 
            [namespaceURI] => 
            [prefix] => 
            [localName] => 
            [baseURI] => /home/mydomain/domains/webverder.nl/public_html/egm/Twinfield/
            [textContent] => 10666Lennart TesterDEBhttp://webverder.nl10falseVL1lennart@webverder.nlNLTestCity1212 AB010-12345010-1234test@email.comTesting field 1Testing field 2Testing field 3NLA001652
        )

)
```

Only i don't really know how to use this data to debug my problem.

Do you have any tips on how to approach this ?


Thanks in advance,

Kind Regards,

Lennart

**Comment by zogot** [comment]
Hi Lennart,

The Response class has a method to retrieve the base DOMDocument object https://github.com/pronamic/twinfield/blob/develop/src/Pronamic/Twinfield/Response/Response.php#L45, you can read more about it here: http://php.net/manual/en/class.domdocument.php there are a few helpful methods there. 

You should be able to call ->saveXML() method on that response to see the full XML that Twinfield has given you. Chances are in there it will have information about what might be wrong.

```php
$response = $customerFactory->getResponse();
var_dump($response->getResponseDocument()->saveXML());
```

**Comment by WebVerder** [comment]
Hi Zogot,

Thanks for your reply, i'm gonna look into this!

**Comment by jbrocker** [comment]
I'm getting the same error: (object value omitted)
When trying the example code from the readme (after removing the obsolete setCocNumber and setID) it throws the error. My guess something is wrong before it was sent to Twinfield. 

Retrieving the customers through listAll() does not through an error. 

This is my error:
`object(Pronamic\Twinfield\Response\Response)#24 (1) {
  ["responseDocument":"Pronamic\Twinfield\Response\Response":private]=>
  object(DOMDocument)#23 (34) {
    ["doctype"]=>
    NULL
    ["implementation"]=>
    string(22) "(object value omitted)"
    ["documentElement"]=>
    string(22) "(object value omitted)"
    ["actualEncoding"]=>
    NULL
    ["encoding"]=>
    NULL
    ["xmlEncoding"]=>
    NULL
    ["standalone"]=>
    bool(true)
    ["xmlStandalone"]=>
    bool(true)
    ["version"]=>
    string(3) "1.0"
    ["xmlVersion"]=>
    string(3) "1.0"
    ["strictErrorChecking"]=>
    bool(true)
    ["documentURI"]=>
    string(52) "/var/www/mttm/invoice2pdf.mttm.nu/webroot/twinfield/"
    ["config"]=>
    NULL
    ["formatOutput"]=>
    bool(false)
    ["validateOnParse"]=>
    bool(false)
    ["resolveExternals"]=>
    bool(false)
    ["preserveWhiteSpace"]=>
    bool(true)
    ["recover"]=>
    bool(false)
    ["substituteEntities"]=>
    bool(false)
    ["nodeName"]=>
    string(9) "#document"
    ["nodeValue"]=>
    NULL
    ["nodeType"]=>
    int(9)
    ["parentNode"]=>
    NULL
    ["childNodes"]=>
    string(22) "(object value omitted)"
    ["firstChild"]=>
    string(22) "(object value omitted)"
    ["lastChild"]=>
    string(22) "(object value omitted)"
    ["previousSibling"]=>
    NULL
    ["attributes"]=>
    NULL
    ["ownerDocument"]=>
    NULL
    ["namespaceURI"]=>
    NULL
    ["prefix"]=>
    string(0) ""
    ["localName"]=>
    NULL
    ["baseURI"]=>
    string(52) "/var/www/mttm/invoice2pdf.mttm.nu/webroot/twinfield/"
    ["textContent"]=>
    string(296) "220003JopDEBhttp://leon.rowland.nlTEST29121514false1jop@brocker.nl2customersupplierinheritfalsenone11300false22000313000truefalseNLTestCity1212 AB0642200265factuur@brocker.nlTesting field 1Testing field 2JLJ Brocker123456NLNL81KNAB0741816326db53e209-7d5d-4536-b114-16eee56f4bectruenormal00000true"
  }
}`

Any thoughts?

**Comment by remcotolsma** [comment]
We are currently cleaning up old open issues within the @pronamic organization and that is how we came across this issue, this may already have been resolved in the https://github.com/php-twinfield/twinfield library.
