### ISSUE TITLE
CreditManagement cannot always be mapped to Customer

### ISSUE THREAD

**Issue by stephangroen** [pronamic/twinfield#38]
CustomerMapper assumes a `creditmanagement` tag is always present on the returned XML from Twinfield when retrieving a customer. This is not necessarily the case. When this is not the case you will get a `Fatal error: Call to a member function getElementsByTagName() on null in CustomerMapper.php on line 111`.

This can be fixed by checking if `$creditManagementElement` is null near line 93 (after assigning the variable) and only try to map the element when it's not.

If you like I can submit a PR to fix this.

**Comment by remcotolsma** [comment]
We are currently cleaning up old open issues within the @pronamic organization and that is how we came across this issue, this may already have been resolved in the https://github.com/php-twinfield/twinfield library.
