### ISSUE TITLE
Freetext fields in the Transaction is not supported by the api

### ISSUE THREAD

**Issue by muhammedeminakbulut** [pronamic/twinfield#41]
I get this error message.

`<freetext1 msgtype="error" msg="Kostenplaats is niet toegestaan in de koptekst." result="0" /><freetext2 msgtype="error" msg="Uw referentie is niet toegestaan in de koptekst." result="0" /><freetext3 msgtype="error" msg="Extra omschrijving is niet toegestaan in de koptekst." result="0" />`

**Comment by Peter-Twinfield** [comment]
Don't know if this is still an issue? The use of freetext fields is disabled. Via the UI you can set these fields to allowed in the option Transaction Type.

**Comment by remcotolsma** [comment]
We are currently cleaning up old open issues within the @pronamic organization and that is how we came across this issue, this may already have been resolved in the https://github.com/php-twinfield/twinfield library.
