### ISSUE TITLE
Laravel providers

### ISSUE THREAD

**Issue by BetaBugish** [pronamic/twinfield#48]
I'm facing a bunch of projects that seem to have Laravel as their primary framework. Do you guys mind if I publish the providers I wrote for this library? ( In a different repository ).

It essentially just glues this project to Laravel's DI container, allowing for IoC.
Docs found here: https://laravel.com/docs/5.2/container

I obviously don't intend to redistribute any of your code. Just my wrapper around the library to allow for things like Facades, simplifying the usage of the library when used in combination with Laravel.

**Comment by remcotolsma** [comment]
> Do you guys mind if I publish the providers I wrote for this library? ( In a different repository ).

I don't mind.
