### ISSUE TITLE
How to expand CustomerFactory to get more info like the collect mandate?

### ISSUE THREAD

**Issue by Ma-ve** [pronamic/twinfield#55]
[As seen here](https://c3.twinfield.com/webservices/documentation/#/ApiReference/Masters/Customers#Create-Update-Delete), I'd like to retrieve the collectmandate set for a customer. As the CustomerFactory doesn't extend the FinderFactory, and the FinderFactory isn't out of the box usable, how would one expand CustomerFactory to get more info, like the financials, bank and collectmandate information?

I'm not too well versed in WSDL, and I'm pulling my hairs out figuring this out.

**Comment by remcotolsma** [comment]
We are currently cleaning up old open issues within the @pronamic organization and that is how we came across this issue, this may already have been resolved in the https://github.com/php-twinfield/twinfield library.
