### ISSUE TITLE
Is this still  maintained? Can't get it to work

### ISSUE THREAD

**Issue by SativaNL** [pronamic/twinfield#56]
I can't get the simple examples to work.

```
<?php

use Pronamic\Twinfield\Secure\Config;
use Pronamic\Twinfield\Customer as TwinfieldCustomer;


class api {	
	public function finalTest() {

        // Config object prepared and passed into the CustomerFactory
        $customerFactory = new TwinfieldCustomer\CustomerFactory($config);

        $customers = $customerFactory->listAll();
        print_r($customers);
        return false;
    }
```

Error:
Class 'Pronamic\Twinfield\Customer\CustomerFactory not found

I've tried everything, but it isn't working (PHP 7)

What am I doing wrong?
Thnx

**Comment by julesbloemen** [comment]
Just notice the same issue. Fetching the data with composer does not include everything. My guess versions are not updated with extra files.

**Comment by casperbakker** [comment]
Composer version is indeed very old, this library has many more new files.

**Comment by casperbakker** [comment]
We created a fork that has proper versions for Composer/Packagist: https://github.com/picqer/twinfield-php-client

You can use it with `composer require picqer/twinfield-php-client`

Not trying to steal the project, we just needed this for ourselves to get rid of our private repositories cause that slows down Composer a lot.

**Comment by remcotolsma** [comment]
We are currently cleaning up old open issues within the @pronamic organization and that is how we came across this issue, the https://github.com/php-twinfield/twinfield library is also a fairly active alternative.
